  
google_project_id = "caramel-anvil-289323"
region = "us-east1"
cluster_version = "1.16"
cluster_node_count = "2"
google_credentials = "olga-service-account.json"
cluster_network = "default"
subnetwork = "default"
cluster_name = "gke-cluster-4"
machine_type = "n1-standard-2"
deployment_environment = "test"
google_bucket_name = "us-east-bucket"
